server {
    listen 80;
    server_name y-a-quoi-dans-le-frigo.fr y-a-quoi-dans-le-frigo.com y-a-quoi-dans-le-frigo.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    return 301 https://y-a-quoi-dans-le-frigo.fr$request_uri;
}

server {
    listen 443 ssl;
    server_name y-a-quoi-dans-le-frigo.fr y-a-quoi-dans-le-frigo.com y-a-quoi-dans-le-frigo.online;

    ssl_certificate /etc/letsencrypt/live/y-a-quoi-dans-le-frigo.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/y-a-quoi-dans-le-frigo.fr/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
