server {
    listen 80;
    server_name y-a-quoi-dans-le-frigo.fr y-a-quoi-dans-le-frigo.com y-a-quoi-dans-le-frigo.online;

    # redirect every HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name y-a-quoi-dans-le-frigo.fr y-a-quoi-dans-le-frigo.com y-a-quoi-dans-le-frigo.online;

    # SSL certificates
    ssl_certificate /etc/letsencrypt/live/y-a-quoi-dans-le-frigo.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/y-a-quoi-dans-le-frigo.fr/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # backend (API) routes
    location /api {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # frontend routes (React)
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Gestion du routage React côté client
        rewrite ^/(.*) /$1 break;
        proxy_intercept_errors on;
        error_page 404 =200 /index.html;
    }
}
