name: master auto-deploy on PC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 77.195.235.151 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to PC2
        run: |
          ssh just1@77.195.235.151 << 'EOF'
            cd /home/just1/Documents/dev/y-a-quoi-dans-le-frigo
            git pull origin master
            docker-compose down
            docker-compose up -d --build
          EOF